CREATE DATABASE I2B2DB_USR;
USE I2B2DB_USR;
CREATE LOGIN I2B2DB_USR WITH PASSWORD = 'I2B2DB_PWD', CHECK_POLICY=OFF;
--CREATE SCHEMA I2B2DB_USR;
CREATE USER I2B2DB_USR FOR LOGIN I2B2DB_USR;
GRANT ALTER TO I2B2DB_USR;
GRANT CONTROL TO I2B2DB_USR;

--GRANT ALTER ON SCHEMA::dbo TO I2B2DB_USR;
--ALTER USER I2B2DB_USR WITH DEFAULT_SCHEMA = dbo;
--ALTER AUTHORIZATION ON SCHEMA::dbo TO I2B2DB_USR;
